### PR TITLE
Fix case where holdingsStatementsForSupplements doesn't have a statement

### LINKED ISSUE #873: Fix FOLIO indexing
We're unable to index the instance with the hrid `a10362341`:

```
    /opt/app/indexer/searchworks_traject_indexer/shared/bundle/ruby/3.1.0/gems/ruby-kafka-1.5.0/lib/kafka/consumer.rb:252:in `rescue in block (4 levels) in each_message'
    Caused by
    KeyError: key not found: "statement"
    /opt/app/indexer/searchworks_traject_indexer/releases/20230508185150/lib/folio/mhld_builder.rb:70:in `fetch'
```

Here's a fragment of the holdings statements on the instance:

```
      "holdingsStatements"=>[{"staffNote"=>"Send to cataloging to receive and update holdings. Library keeps latest replacement volumes only. Latest volumes route to Grundfest", "statement"=>"v.1, 11"}],
      "statisticalCodeIds"=>[],
      "administrativeNotes"=>[],
      "effectiveLocationId"=>"5ecf146b-ce87-42f2-aa63-00d085e82d81",
      "permanentLocationId"=>"5ecf146b-ce87-42f2-aa63-00d085e82d81",
      "suppressFromDiscovery"=>false,
      "holdingsStatementsForIndexes"=>[],
      "holdingsStatementsForSupplements"=>[{"note"=>"Library keeps latest only", "staffNote"=>"Library keeps latest supplement only. Insert outdated to transfer shelf flag"}]}],
```

### PR DESCRIPTION
**Pull request by jcoyne**
Fixes #873

### CODE REVIEW

File: lib/folio/mhld_builder.rb [hunk 1]
```diff
@@ -67,7 +67,7 @@ def statments_for_index(holding)
     end
 
     def statements_for_supplements(holding)
-      holding.fetch('holdingsStatementsForSupplements').map { |statement| "Supplement: #{statement.fetch('statement')}" }
+      holding.fetch('holdingsStatementsForSupplements').filter_map { |statement| "Supplement: #{statement.fetch('statement')}" if statement.key?('statement') }
```
Comment (cbeer) [inline lib/folio/mhld_builder.rb:70]: Could this same thing happen for `holdingsStatementsForIndexes` above?

Comment (jcoyne) [reply lib/folio/mhld_builder.rb:70]: In theory, yes, but we haven't seen any data like that yet.
