### PR TITLE
Refactor course reserve fetching to fix item duplication

### LINKED ISSUE #1168: Duplicate items for CREZ items
E.g. https://searchworks.stanford.edu/view/13956859

### PR DESCRIPTION
**Pull request by thatbudakguy**
Fixes #1168 

Tested with [a13956859](https://searchworks.stanford.edu/view/13956859).

Before (second two items on reserve have duplicates in output from postgres query):
```sh
$ ./script/download_folio_record.rb a13956859 | jq '.items[].barcode'
"36105228813718"
"36105237776146"
"36105237776146"
"36105237776146"
"36105228813700"
"36105228813700"
"36105228813700"
```

After:
```sh
$ ./script/download_folio_record.rb a13956859 | jq '.items[].barcode'
"36105228813718"
"36105237776146"
"36105228813700"
```

### CODE REVIEW

File: script/download_folio_record.rb [hunk 1]
```diff
@@ -2,11 +2,17 @@
 # frozen_string_literal: true
 
 require 'json'
-require_relative '../config/boot'
```
Comment (thatbudakguy) [inline script/download_folio_record.rb:5]: this loads a bunch of things, including honeybadger, which prints its startup message and pollutes the output so it can't be parsed as JSON. if there's any easier way to disable that, i'd be happy to do it.

File: lib/folio_record.rb [hunk 2]
```diff
@@ -123,15 +123,18 @@ def to_honeybadger_context
...
-    record.fetch('courses', []).map do |course|
-      {
-        course_name: course['name'],
-        course_id: course['courseNumber'],
-        instructors: course['instructorObjects'].pluck('name'),
-        listing_id: course['courseListingId'],
-        reserve_desk: course.dig('location', 'code')
-      }
+    item_courses = items.flat_map do |item|
+      item['courses'].map do |course|
```
Comment (thatbudakguy) [inline lib/folio_record.rb:127]: maybe the inner loop means this should now be memoized?

**Comment by cbeer** [comment]
Could you run `folio_postgres_reader_spec` and report any timing changes?

**Comment by thatbudakguy** [comment]
On `main`:
```
Traject::FolioPostgresReader
  with a chunk (of about 2.5k items)
       user     system      total        real
   0.694790   0.266639   0.961429 ( 20.365096)
    creates FolioRecords
  with a delta for a whole day
       user     system      total        real
   0.004211   0.002664   0.006875 ( 62.678245)
    creates FolioRecords (FAILED - 1)
```

On this branch:
```
Traject::FolioPostgresReader
  with a chunk (of about 2.5k items)
       user     system      total        real
   0.706212   0.244096   0.950308 ( 31.438429)
    creates FolioRecords
  with a delta for a whole day
       user     system      total        real
   0.002823   0.002699   0.005522 ( 62.655527)
    creates FolioRecords (FAILED - 1)
```

...does this seem right? there is a difference with the smaller set, but the larger set is about the same, and over the 60-sec mark in both cases.

**Comment by thatbudakguy** [comment]
ran it again and got a result closer to `main`'s:
```
Traject::FolioPostgresReader
  with a chunk (of about 2.5k items)
       user     system      total        real
   0.702742   0.261718   0.964460 ( 24.159429)
    creates FolioRecords
  with a delta for a whole day
       user     system      total        real
   0.002993   0.002395   0.005388 ( 62.097989)
    creates FolioRecords (FAILED - 1)
```
