### PR TITLE
Don't create mhld_display when there are no holdings statements

### LINKED ISSUE #884: [searchworks_traject_indexer/stage] NoMethodError: undefined method `fetch' for nil:NilClass
## Backtrace

    line 18 of [PROJECT_ROOT]/lib/folio/mhld_builder.rb: block in build
    line 17 of [PROJECT_ROOT]/lib/folio/mhld_builder.rb: map
    line 17 of [PROJECT_ROOT]/lib/folio/mhld_builder.rb: build

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/57331/faults/95841937)

### PR DESCRIPTION
**Pull request by jcoyne**
Fixes #884

### CODE REVIEW

File: lib/folio/mhld_builder.rb [hunk 1]
```diff
@@ -30,7 +30,10 @@ def build
     # Remove suppressed record and electronic records
```
Comment (marlo-longley) [inline lib/folio/mhld_builder.rb:30]: # Remove suppressed records, electronic records, and records with no holdings statement
