### PR TITLE
Call Traject's first_only on arrays rather than nodesets

### LINKED ISSUE #1087: Fix indexing for selected items
These items aren't indexing right, and Solr complains:

> org.apache.solr.common.SolrException: ERROR: [doc=bh957gz2544] Error adding field 'copyright_year_isi'='[198019821984]' msg=For input string: "198019821984"

```
bh957gz2544
bj788pb4930
dz167nj0081
fs725jm0883
gs905yg7715
gz593pq0500
hw872qg4168
jc545vc9641
jt357yn4747
kt259dk5765
mc155ws9482
mf589bk2522
mp889qt5652
qx421cw0384
sh027xz0057
sr684bp5460
yy345wr7867
```

### PR DESCRIPTION
**Pull request by marlo-longley**
Fixes #1087

### CODE REVIEW

File: lib/traject/config/sdr_config.rb [hunk 1]
```diff
@@ -77,7 +77,9 @@ def stanford_mods(method, *args, default: nil)
 
 def mods_xpath(xpath)
   lambda do |resource, accumulator, _context|
-    accumulator << resource.mods.xpath(xpath, mods: 'http://www.loc.gov/mods/v3')
+    # Convert the xpath result (a Nokogiri nodeset) to a plain array.
+    # This allows traject methods like first_only to work properly.
+    accumulator.concat(resource.mods.xpath(xpath, mods: 'http://www.loc.gov/mods/v3')).to_a
```
Comment (cbeer) [inline lib/traject/config/sdr_config.rb:82]:
```suggestion
    accumulator.concat(resource.mods.xpath(xpath, mods: 'http://www.loc.gov/mods/v3'). to_a)
```

Is the `#to_a` misplaced, or maybe it's unnecessary (because concat calls it implicitly)

Comment (marlo-longley) [reply lib/traject/config/sdr_config.rb]: @cbeer thanks - you're right, .concat does the conversion. With this change everything works the same as expected.
