### PR TITLE
Handle the case where the piece does not have enumeration

### LINKED ISSUE #901: [searchworks_traject_indexer/stage] KeyError: key not found: "enumeration"
## Backtrace

    line 83 of [PROJECT_ROOT]/lib/folio/mhld_builder.rb: fetch
    line 83 of [PROJECT_ROOT]/lib/folio/mhld_builder.rb: latest_received
    line 25 of [PROJECT_ROOT]/lib/folio/mhld_builder.rb: block in build

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/57331/faults/96148469)

### PR DESCRIPTION
**Pull request by jcoyne**
Fixes #901

### CODE REVIEW

File: lib/folio/mhld_builder.rb [hunk 1]
```diff
@@ -80,7 +80,11 @@ def latest_received(holding_id)
       # NOTE: We saw some piece records without 'chronology'. Was this just test data?
       pieces = pieces_per_holding.fetch(holding_id, []).filter_map { |piece| piece.merge(date: Date.parse(piece.fetch('chronology'))) if piece['chronology'] }
       latest_piece = pieces.max_by { |piece| piece.fetch(:date) }
-      "#{latest_piece.fetch('enumeration')} (#{latest_piece.fetch('chronology')})" if latest_piece
+      return unless latest_piece
+
+      enumeration = latest_piece['enumeration'] # may not be present
+      cronology = latest_piece.fetch('chronology')
+      enumeration ? "#{enumeration} (#{cronology})" : cronology
```
Comment (cbeer) [inline lib/folio/mhld_builder.rb:87]:
```suggestion
      chronology = latest_piece.fetch('chronology')
      enumeration ? "#{enumeration} (#{chronology})" : chronology
```
